/* The shipped 40-level campaign. Generated — do not hand-edit.
 *
 *   node tools/make_40.js --out configLevel_gen40 --tries 10
 *   node tools/pack_40.js
 *
 * Teaching order: hidden cars from level 9, coloured columns from 21, locked
 * columns from 31. Every new mechanic lands on a step DROP so the level that
 * introduces it is easier than the one before it. Budgets are fitted to each
 * step's win-rate band by bisection rather than by multiplying the optimum,
 * because the ladder's slack numbers were measured before these two
 * mechanics existed. Measured curve and per-level numbers:
 * configLevel_gen40/README.md
 */
(function (global) {
  'use strict';

  var LEVELS = [
    { id: 1, tier: 1, cols: 3, rows: 3, moves: 10, theme: "city", pad: "magenta",
      grid: [["magenta","purple","magenta"],["purple","pink","REV"],["purple","pink","pink"]] },
    { id: 2, tier: 1, cols: 3, rows: 3, moves: 10, theme: "city", pad: "green",
      grid: [["violet","violet","violet"],["green","lime","lime"],["lime","green","REV"]] },
    { id: 3, tier: 2, cols: 4, rows: 3, moves: 23, theme: "city", pad: "cyan",
      grid: [["REV","mint","mint"],["teal","cyan","blue"],["cyan","teal","blue"],["teal","mint","blue"]] },
    { id: 4, tier: 2, cols: 4, rows: 3, moves: 15, theme: "city", pad: "yellow",
      grid: [["orange","yellow","navy"],["navy","orange","blue"],["REV","yellow","orange"],["blue","navy","blue"]] },
    { id: 5, tier: 3, cols: 4, rows: 4, moves: 25, theme: "city", pad: "beige",
      grid: [["orange","brown","red","orange"],["brown","red","red","brown"],["brown","beige","red","orange"],["beige","orange","REV","beige"]] },
    { id: 6, tier: 3, cols: 4, rows: 4, moves: 23, theme: "city", pad: "gray",
      grid: [["magenta","REV","beige","white"],["gray","magenta","gray","gray"],["white","beige","magenta","beige"],["beige","white","white","magenta"]] },
    { id: 7, tier: 4, cols: 5, rows: 4, moves: 27, theme: "city", pad: "lime",
      grid: [["violet","lime","pink","magenta"],["purple","pink","magenta","purple"],["purple","purple","pink","violet"],["magenta","REV","lime","magenta"],["violet","violet","lime","pink"]] },
    { id: 8, tier: 4, cols: 5, rows: 4, moves: 25, theme: "city", pad: "mint",
      grid: [["lime","mint","violet","green"],["lime","teal","lime","violet"],["green","REV","teal","mint"],["green","teal","teal","green"],["lime","mint","violet","violet"]] },
    { id: 9, tier: 3, cols: 5, rows: 4, moves: 27, theme: "city", pad: "blue",
      grid: [["?mint","cyan","REV","teal"],["teal","cyan","teal","mint"],["mint","teal","navy","cyan"],["cyan","navy","navy","blue"],["blue","?blue","mint","navy"]] },
    { id: 10, tier: 4, cols: 5, rows: 4, moves: 29, theme: "city", pad: "orange",
      grid: [["orange","navy","navy","red"],["yellow","orange","blue","?navy"],["yellow","REV","red","red"],["yellow","?blue","orange","?blue"],["blue","navy","yellow","red"]] },
    { id: 11, tier: 5, cols: 5, rows: 5, moves: 27, theme: "suburb", pad: "gray",
      grid: [["orange","brown","brown","orange","orange"],["brown","red","red","gray","red"],["brown","red","beige","red","gray"],["REV","beige","beige","orange","beige"],["gray","brown","gray","beige","orange"]] },
    { id: 12, tier: 5, cols: 5, rows: 5, moves: 33, theme: "suburb", pad: "white",
      grid: [["magenta","gray","gray","beige","gray"],["pink","pink","magenta","white","REV"],["pink","magenta","white","white","magenta"],["beige","beige","white","gray","beige"],["gray","magenta","beige","pink","pink"]] },
    { id: 13, tier: 6, cols: 5, rows: 5, moves: 34, theme: "suburb", pad: "purple",
      grid: [["pink","magenta","purple","magenta","violet"],["lime","lime","violet","REV","pink"],["purple","magenta","pink","magenta","purple"],["magenta","violet","lime","pink","violet"],["purple","pink","lime","violet","lime"]] },
    { id: 14, tier: 4, cols: 5, rows: 5, moves: 33, theme: "suburb", pad: "lime",
      grid: [["green","teal","violet","violet","violet"],["lime","?REV","green","lime","mint"],["?green","violet","green","mint","mint"],["lime","green","?teal","mint","mint"],["teal","teal","lime","violet","teal"]] },
    { id: 15, tier: 6, cols: 5, rows: 5, moves: 30, theme: "suburb", pad: "navy",
      grid: [["mint","teal","navy","mint","blue"],["mint","teal","mint","teal","teal"],["REV","cyan","blue","teal","cyan"],["cyan","blue","cyan","cyan","blue"],["mint","navy","blue","navy","navy"]] },
    { id: 16, tier: 7, cols: 5, rows: 5, moves: 34, theme: "suburb", pad: "yellow",
      grid: [["red","navy","blue","navy","blue"],["navy","orange","blue","red","navy"],["orange","yellow","red","orange","blue"],["red","REV","orange","yellow","yellow"],["red","blue","orange","navy","yellow"]] },
    { id: 17, tier: 5, cols: 5, rows: 4, moves: 24, theme: "suburb", pad: "beige",
      grid: [["orange","gray","brown","beige"],["REV","brown","red","red"],["orange","brown","orange","red"],["red","beige","gray","beige"],["orange","gray","gray","brown"]] },
    { id: 18, tier: 6, cols: 5, rows: 4, moves: 21, theme: "suburb", pad: "magenta",
      grid: [["pink","gray","beige","gray"],["beige","white","gray","?magenta"],["magenta","gray","white","?beige"],["REV","white","pink","white"],["beige","?pink","?pink","magenta"]] },
    { id: 19, tier: 7, cols: 5, rows: 5, moves: 33, theme: "suburb", pad: "violet",
      grid: [["?violet","lime","purple","magenta","magenta"],["lime","purple","magenta","REV","?pink"],["violet","pink","purple","purple","pink"],["?lime","violet","?violet","magenta","?pink"],["lime","pink","lime","magenta","purple"]] },
    { id: 20, tier: 6, cols: 6, rows: 4, moves: 26, theme: "suburb", pad: "green",
      grid: [["green","mint","cyan","lime"],["teal","cyan","lime","teal"],["violet","cyan","green","mint"],["lime","teal","violet","violet"],["mint","green","mint","teal"],["cyan","REV","violet","lime"]] },
    { id: 21, tier: 5, cols: 5, rows: 4, moves: 20, theme: "suburb", pad: "blue",
      coloredCols: [{"col":2,"color":"mint"}],
      grid: [["mint","REV","cyan","cyan"],["teal","mint","teal","teal"],["mint","navy","blue","teal"],["blue","cyan","navy","mint"],["navy","cyan","blue","navy"]] },
    { id: 22, tier: 6, cols: 6, rows: 5, moves: 40, theme: "suburb", pad: "yellow",
      coloredCols: [{"col":0,"color":"blue"},{"col":2,"color":"navy"}],
      grid: [["?orange","brown","blue","blue","red"],["blue","yellow","red","REV","navy"],["blue","red","navy","?orange","brown"],["blue","navy","orange","yellow","orange"],["navy","brown","yellow","red","brown"],["red","navy","orange","yellow","brown"]] },
    { id: 23, tier: 6, cols: 6, rows: 5, moves: 43, theme: "suburb", pad: "red",
      coloredCols: [{"col":1,"color":"orange"},{"col":3,"color":"red"}],
      grid: [["beige","beige","red","beige","gray"],["brown","brown","?red","gray","?REV"],["white","brown","orange","orange","white"],["brown","orange","orange","red","white"],["gray","white","gray","beige","gray"],["?brown","beige","red","white","orange"]] },
    { id: 24, tier: 7, cols: 6, rows: 5, moves: 61, theme: "suburb", pad: "magenta",
      coloredCols: [{"col":1,"color":"beige"},{"col":3,"color":"gray"},{"col":5,"color":"white"}],
      grid: [["magenta","gray","pink","purple","beige"],["white","pink","magenta","beige","beige"],["purple","purple","gray","pink","pink"],["white","purple","purple","beige","magenta"],["REV","beige","pink","magenta","gray"],["gray","white","gray","white","white"]] },
    { id: 25, tier: 5, cols: 6, rows: 5, moves: 38, theme: "suburb", pad: "purple",
      coloredCols: [{"col":5,"color":"magenta"}],
      grid: [["green","pink","violet","green","magenta"],["lime","pink","magenta","lime","purple"],["purple","pink","green","violet","lime"],["REV","purple","purple","pink","violet"],["violet","lime","green","green","lime"],["pink","magenta","violet","magenta","magenta"]] },
    { id: 26, tier: 7, cols: 6, rows: 5, moves: 36, theme: "suburb", pad: "teal",
      coloredCols: [{"col":1,"color":"violet"}],
      grid: [["cyan","lime","cyan","?green","?violet"],["lime","violet","mint","violet","teal"],["cyan","green","cyan","green","teal"],["mint","green","lime","violet","lime"],["green","cyan","violet","teal","REV"],["mint","mint","lime","mint","teal"]] },
    { id: 27, tier: 7, cols: 6, rows: 4, moves: 25, theme: "suburb", pad: "yellow",
      coloredCols: [{"col":0,"color":"mint"},{"col":4,"color":"teal"}],
      grid: [["mint","navy","blue","mint"],["cyan","?yellow","blue","cyan"],["?teal","navy","?cyan","yellow"],["blue","yellow","teal","blue"],["navy","teal","teal","mint"],["REV","mint","cyan","navy"]] },
    { id: 28, tier: 8, cols: 6, rows: 5, moves: 41, theme: "suburb", pad: "red",
      coloredCols: [{"col":0,"color":"blue"},{"col":3,"color":"navy"}],
      grid: [["brown","navy","red","brown","red"],["red","orange","REV","orange","orange"],["yellow","?orange","navy","yellow","blue"],["?blue","navy","navy","blue","navy"],["brown","blue","yellow","yellow","red"],["yellow","blue","brown","brown","orange"]] },
    { id: 29, tier: 6, cols: 5, rows: 5, moves: 55, theme: "suburb", pad: "red",
      coloredCols: [{"col":3,"color":"orange"}],
      grid: [["orange","red","beige","beige","beige"],["beige","red","orange","orange","REV"],["brown","orange","gray","brown","brown"],["brown","beige","gray","gray","orange"],["brown","red","red","gray","gray"]] },
    { id: 30, tier: 8, cols: 6, rows: 5, moves: 44, theme: "suburb", pad: "pink",
      coloredCols: [{"col":1,"color":"beige"},{"col":2,"color":"gray"}],
      grid: [["beige","white","white","?white","gray"],["beige","purple","gray","magenta","purple"],["pink","beige","pink","magenta","REV"],["white","white","purple","magenta","gray"],["purple","pink","gray","beige","gray"],["pink","magenta","beige","purple","?magenta"]] },
    { id: 31, tier: 6, cols: 6, rows: 4, moves: 38, theme: "suburb", pad: "violet",
      lockedCols: [{"col":1,"need":1}],
      coloredCols: [{"col":3,"color":"magenta"},{"col":5,"color":"pink"}],
      grid: [["violet","purple","purple","lime"],["REV","green","green","magenta"],["pink","pink","green","violet"],["green","magenta","magenta","violet"],["purple","purple","lime","lime"],["magenta","lime","pink","pink"]] },
    { id: 32, tier: 7, cols: 6, rows: 4, moves: 36, theme: "suburb", pad: "teal",
      lockedCols: [{"col":3,"need":1}],
      coloredCols: [{"col":0,"color":"violet"},{"col":2,"color":"lime"}],
      grid: [["green","violet","violet","teal"],["violet","lime","?green","?green"],["lime","cyan","mint","lime"],["mint","cyan","lime","teal"],["REV","teal","green","mint"],["?violet","cyan","cyan","mint"]] },
    { id: 33, tier: 8, cols: 6, rows: 5, moves: 49, theme: "suburb", pad: "navy",
      coloredCols: [{"col":1,"color":"mint"},{"col":2,"color":"teal"},{"col":4,"color":"cyan"}],
      grid: [["mint","teal","navy","teal","cyan"],["cyan","mint","cyan","mint","blue"],["yellow","mint","yellow","blue","blue"],["navy","navy","blue","REV","teal"],["cyan","navy","yellow","cyan","teal"],["blue","yellow","yellow","mint","teal"]] },
    { id: 34, tier: 8, cols: 6, rows: 5, moves: 37, theme: "suburb", pad: "navy",
      lockedCols: [{"col":0,"need":1}],
      coloredCols: [{"col":3,"color":"blue"},{"col":5,"color":"navy"}],
      grid: [["brown","orange","yellow","red","navy"],["brown","REV","blue","navy","brown"],["brown","yellow","red","orange","red"],["blue","yellow","brown","blue","blue"],["orange","orange","red","red","yellow"],["orange","navy","yellow","navy","blue"]] },
    { id: 35, tier: 7, cols: 6, rows: 5, moves: 47, theme: "suburb", pad: "gray",
      lockedCols: [{"col":0,"need":1},{"col":4,"need":2}],
      coloredCols: [{"col":2,"color":"orange"},{"col":5,"color":"red"}],
      grid: [["brown","beige","orange","beige","white"],["red","gray","orange","white","beige"],["brown","white","orange","brown","red"],["white","gray","beige","orange","beige"],["gray","orange","brown","REV","brown"],["red","red","white","gray","red"]] },
    { id: 36, tier: 9, cols: 6, rows: 5, moves: 45, theme: "suburb", pad: "magenta",
      lockedCols: [{"col":2,"need":1}],
      coloredCols: [{"col":3,"color":"beige"},{"col":4,"color":"gray"},{"col":5,"color":"white"}],
      grid: [["purple","purple","magenta","gray","gray"],["beige","pink","?beige","?pink","beige"],["white","pink","pink","magenta","magenta"],["pink","white","gray","magenta","?purple"],["gray","?purple","gray","purple","beige"],["?beige","white","?white","REV","white"]] },
    { id: 37, tier: 8, cols: 6, rows: 4, moves: 29, theme: "suburb", pad: "green",
      lockedCols: [{"col":4,"need":2}],
      coloredCols: [{"col":1,"color":"magenta"},{"col":3,"color":"pink"}],
      grid: [["?pink","purple","green","?magenta"],["purple","magenta","magenta","?violet"],["lime","?violet","pink","purple"],["pink","purple","?pink","?lime"],["?magenta","lime","violet","lime"],["green","green","REV","violet"]] },
    { id: 38, tier: 9, cols: 6, rows: 5, moves: 36, theme: "suburb", pad: "mint",
      lockedCols: [{"col":0,"need":1},{"col":5,"need":1}],
      coloredCols: [{"col":1,"color":"violet"},{"col":3,"color":"lime"}],
      grid: [["cyan","mint","green","green","green"],["mint","violet","violet","cyan","cyan"],["cyan","teal","REV","violet","violet"],["teal","lime","lime","violet","lime"],["mint","lime","teal","lime","green"],["teal","cyan","teal","green","mint"]] },
    { id: 39, tier: 9, cols: 6, rows: 5, moves: 44, theme: "suburb", pad: "yellow",
      lockedCols: [{"col":1,"need":1}],
      coloredCols: [{"col":0,"color":"mint"},{"col":5,"color":"teal"}],
      grid: [["teal","?yellow","?navy","teal","teal"],["navy","cyan","cyan","cyan","yellow"],["?cyan","navy","mint","?blue","mint"],["navy","mint","blue","REV","?blue"],["navy","teal","?cyan","?blue","teal"],["yellow","yellow","mint","mint","?blue"]] },
    { id: 40, tier: 10, cols: 6, rows: 5, moves: 36, theme: "suburb", pad: "blue",
      lockedCols: [{"col":0,"need":2}],
      coloredCols: [{"col":1,"color":"blue"},{"col":2,"color":"navy"},{"col":4,"color":"yellow"},{"col":5,"color":"orange"}],
      grid: [["red","brown","brown","?yellow","navy"],["blue","orange","orange","REV","blue"],["yellow","?navy","orange","?navy","navy"],["brown","?blue","red","navy","brown"],["brown","red","yellow","yellow","yellow"],["orange","red","orange","red","blue"]] },
  ];

  var S = global.LevelSets;
  if (!S) return;
  S.SETS['gen40'] = {
    name: { vi: '40 level', en: '40 levels' },
    label: { vi: '40 level', en: '40 levels' },
    intent: { vi: 'Bộ đầy đủ 40 level. Xe ẩn từ level 9, cột màu từ 21, cột khoá từ 31 — mỗi cơ chế mới vào ở một bậc tụt.',
              en: 'The full 40-level run. Hidden cars from level 9, coloured columns from 21, locked columns from 31 — each new mechanic arrives on a step drop.' },
    note: '',
    rhythmOn: 'winAvg',
    breathers: [9, 14, 17, 21, 25, 27, 29, 31, 35],
    levels: LEVELS
  };
  /* first in the picker: this is the campaign; the four short sets stay for
   * comparing curves. */
  if (S.order.indexOf('gen40') < 0) S.order.unshift('gen40');
})(typeof self !== 'undefined' ? self : this);
